import React, { useState, useEffect } from 'react';
import axios from 'axios';
import QuestionEditor from './QuestionEditor'; // Import the QuestionEditor component

const ManageQuestions = ({ template, setTemplate }) => {
  const [questions, setQuestions] = useState(template?.questions ?? []);

  // Update questions when template changes
  useEffect(() => {
    setQuestions(template?.questions ?? []);
  }, [template]);

  // Fetch the latest template data from the backend
  const fetchTemplate = async () => {
    try {
      const response = await axios.get(`/api/templates/${template.id}`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` },
      });
      setTemplate(response.data);
    } catch (error) {
      console.error('Error fetching template:', error);
      alert('Failed to load the template.');
    }
  };

  // Save updated questions to the backend
  const saveQuestions = async () => {
    // Prepare the payload by omitting temporary IDs for new questions
    const preparedQuestions = questions.map((q) => {
      // Identify temporary IDs (large numbers generated by Date.now())
      const isTemporaryId = typeof q.id === 'number' && q.id > 1000000000000;
      return {
        ...q,
        id: isTemporaryId ? undefined : q.id, // Omit temporary IDs
      };
    });

    // Validate questions locally
    if (!Array.isArray(preparedQuestions) || preparedQuestions.some((q) => !q.title || !q.type)) {
      console.error('Invalid questions data:', preparedQuestions);
      alert('Error: All questions must have a title and type.');
      return;
    }

    try {
      // Update the template with the sanitized questions
      const response = await axios.put(
        `/api/templates/${template.id}`,
        { questions: preparedQuestions },
        {
          headers: { Authorization: `Bearer ${localStorage.getItem('token')}` },
        }
      );

      if (response.status === 200) {
        await fetchTemplate(); // Refresh the template data
        alert('Questions saved successfully!');
      }
    } catch (error) {
      console.error('Error saving questions:', error);
      alert('Failed to save the questions.');
    }
  };

  // Handle question updates locally
  const handleUpdateQuestions = (updater) => {
    setQuestions((prev) => {
      const updated = typeof updater === "function" ? updater(prev) : updater;
      return updated;
    });
  };

  return (
    <div>
      <h2>Manage Questions</h2>
      {/* Use the QuestionEditor component */}
      <QuestionEditor questions={questions} setQuestions={handleUpdateQuestions} />
      {/* Save Questions Button */}
      <button onClick={saveQuestions} style={{ marginTop: '20px', padding: '10px 20px' }}>
        Save Questions
      </button>
    </div>
  );
};

export default ManageQuestions;